project:
  type: website
  output-dir: docs

website:
  title: "Maryna Mruk"
  navbar:
    left:
      - href: https://shotam.info
        text: ShoTam
   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

